"use client";

import React, { useState, useEffect, useCallback } from "react";
import Image from "next/image";
import { motion, AnimatePresence } from "framer-motion";
import {
  Compass,
  Maximize2,
  X,
  ChevronLeft,
  ChevronRight,
  ArrowRight,
  MapPin,
  Sparkles,
  Globe,
} from "lucide-react";
import { playHapticClick } from "@/lib/sound";

export interface HorizonItem {
  id: string;
  name: string;
  kicker: string;
  title: string;
  description: string;
  imageSrc: string;
  elevation: string;
  hazard: string;
  yield: string;
  infrastructure: string;
  bloomColor: "alpine" | "glacio" | "geode" | "foundry";
  tag: string;
}

export const HORIZONS: HorizonItem[] = [
  {
    id: "alpine-stratigraphy",
    name: "Alpine Highlands & Glacial Falls",
    kicker: "CARTOGRAPHY // ELEVATION Y=320",
    title: "Colossal Biomes. Unbounded Verticality.",
    description:
      "Generated by the Terralith terrain engine, the world erupts from sea level into 320-block vertical mountain spires. Glacial waterfalls carve canyons through golden autumn birch forests and crystalline alpine streams.",
    imageSrc: "/branding/terralith-biomes-cinematic.jpg",
    elevation: "Y=64 to Y=320 (Troposphere)",
    hazard: "Sheer Escarpments & Freezing Mist",
    yield: "Alpine Quartz & Hydro-Kinetic Head Pressure",
    infrastructure: "Terraced Viaducts & Cloud Observatories",
    bloomColor: "alpine",
    tag: "85+ Terralith Biomes",
  },
  {
    id: "glacio-cryo-colony",
    name: "Glacio Cryo-Colony & Biodomes",
    kicker: "AEROSPACE // EXTRASOLAR EXPEDITION",
    title: "Frozen Horizons. Geodesic Life Support.",
    description:
      "Deep-space colonization on the frozen ice planet Glacio. Automated geodesic biodomes nurture warm hydroponic biospheres beneath towering ice spires and emerald auroras orbiting a colossal ringed gas giant.",
    imageSrc: "/branding/glacio-cryo-colony-cinematic.jpg",
    elevation: "Y=82 to Y=190 (Extrasolar Surface)",
    hazard: "-148°C Cryo-Atmosphere & Cosmic Radiation",
    yield: "Sublimated Cryo-Gases & Permafrost Isotopes",
    infrastructure: "Pressurized Biodomes & Aerospace Launch Gantries",
    bloomColor: "glacio",
    tag: "Deep Space Sector",
  },
  {
    id: "subterranean-geode-caverns",
    name: "Deep Caverns & Amethyst Abyss",
    kicker: "SUBTERRANEAN // ELEVATION Y=-64",
    title: "Resonant Crystals. Abyssal Rivers.",
    description:
      "Descending through fractured deepslate brings explorers to colossal geode chambers. Underground turquoise rivers plunge into bottomless abysses illuminated by massive amethyst crystals and soul-lantern walkways.",
    imageSrc: "/branding/deep-caverns-geode-cinematic.jpg",
    elevation: "Y=-12 to Y=-64 (Bedrock Margin)",
    hazard: "Acoustic Shadows & Abyssal Depths",
    yield: "Resonant Amethyst Clusters & Deepslate Diamonds",
    infrastructure: "High-Tension Suspension Bridges & Sump Systems",
    bloomColor: "geode",
    tag: "Subterranean Abyss",
  },
  {
    id: "kinetic-locomotive-foundry",
    name: "Kinetic Locomotive Foundry",
    kicker: "MECHANIZATION // HEAVY TRANSIT WORKS",
    title: "Brass & Steam. Master Assembly.",
    description:
      "High-ceilinged timber factories harness river waterwheels and steam boilers to forge transcontinental locomotives. Precision brass cogwheels and overhead chain hoists assemble rolling stock under streaming morning sunlight.",
    imageSrc: "/branding/kinetic-locomotive-foundry-cinematic.jpg",
    elevation: "Y=68 (River Valley Basin)",
    hazard: "High-Torque Rotational Shear",
    yield: "Standard-Gauge Rolling Stock & Brass Gearing",
    infrastructure: "Overhead Cranes & Dual Track Assembly Bays",
    bloomColor: "foundry",
    tag: "Industrial Machine",
  },
  {
    id: "frontier-aurora-viaduct",
    name: "Aurelia Mountain Viaduct",
    kicker: "CIVIL TRANSIT // HIGH-SPEED CORRIDORS",
    title: "The Iron Artery. Midnight Transit.",
    description:
      "A transcontinental rail corridor spanning mountain chasms. Steam locomotives travel at 45.0 m/s beneath aurora borealis, linking remote survival outposts to central trading ports across living biomes.",
    imageSrc: "/branding/frontier-hero-cinematic.jpg",
    elevation: "Y=142 (Mountain Pass Span)",
    hazard: "Gale-Force Crosswinds & Icing",
    yield: "Automated Bulk Freight & Rapid Passenger Transit",
    infrastructure: "Segmented Stone Viaducts & Optical Signals",
    bloomColor: "alpine",
    tag: "45.0 m/s Transit",
  },
  {
    id: "sovereign-mountain-citadel",
    name: "New Alexandria Sovereign Citadel",
    kicker: "JURISDICTION // CHARTERED REALM",
    title: "Chartered Bastions. Eternal Rule.",
    description:
      "A player-founded mountain empire chartered with 100% mathematical land claims. Illuminated stone bridges and fortress bastions provide complete grief-free sanctuary for thriving civilizations.",
    imageSrc: "/branding/sovereign-city-cinematic.jpg",
    elevation: "Y=110 to Y=236 (Alpine Spur)",
    hazard: "Precipitous Drop-Offs & Siege Chokepoints",
    yield: "Sovereign Commerce & Vault Reserves",
    infrastructure: "Cyclopean Fortress Walls & Spire Bastions",
    bloomColor: "alpine",
    tag: "100% Grief-Proof",
  },
];

interface WorldHorizonsExplorerProps {
  onOpenBlueMapModal?: () => void;
  onOpenJoinModal?: () => void;
}

export function WorldHorizonsExplorer({
  onOpenBlueMapModal,
  onOpenJoinModal,
}: WorldHorizonsExplorerProps) {
  const [activeIndex, setActiveIndex] = useState(0);
  const [lightboxOpen, setLightboxOpen] = useState(false);

  const activeHorizon = HORIZONS[activeIndex];

  const handleSelect = (index: number) => {
    playHapticClick();
    setActiveIndex(index);
  };

  const handleNext = useCallback(() => {
    playHapticClick();
    setActiveIndex((prev) => (prev + 1) % HORIZONS.length);
  }, []);

  const handlePrev = useCallback(() => {
    playHapticClick();
    setActiveIndex((prev) => (prev - 1 + HORIZONS.length) % HORIZONS.length);
  }, []);

  // Keyboard navigation for carousel & lightbox
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === "ArrowRight") handleNext();
      if (e.key === "ArrowLeft") handlePrev();
      if (e.key === "Escape") setLightboxOpen(false);
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [handleNext, handlePrev]);

  const bloomColorClasses = {
    alpine: "from-emerald-500/[0.08] via-teal-500/[0.03]",
    glacio: "from-cyan-500/[0.08] via-sky-500/[0.03]",
    geode: "from-purple-500/[0.08] via-indigo-500/[0.03]",
    foundry: "from-amber-500/[0.08] via-orange-500/[0.03]",
  };

  const badgeColorClasses = {
    alpine: "text-emerald-400 border-emerald-500/20 bg-emerald-500/10",
    glacio: "text-cyan-400 border-cyan-500/20 bg-cyan-500/10",
    geode: "text-purple-400 border-purple-500/20 bg-purple-500/10",
    foundry: "text-amber-400 border-amber-500/20 bg-amber-500/10",
  };

  return (
    <section id="horizons" className="relative py-28 sm:py-36 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto overflow-hidden">
      {/* Dynamic Ambient Background Glow */}
      <div
        className={`absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[900px] h-[550px] bg-radial ${bloomColorClasses[activeHorizon.bloomColor]} to-transparent pointer-events-none blur-3xl transition-colors duration-1000`}
      />

      {/* Section Header with Authenticity Seal */}
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 mb-12 relative z-10">
        <div className="max-w-3xl text-left">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-white/[0.03] border border-white/[0.08] text-zinc-400 font-mono text-[11px] uppercase tracking-widest mb-4 backdrop-blur-md">
            <Compass className="w-3.5 h-3.5 text-cyan-400" />
            PANORAMIC EXPEDITION // 6 WORLD HORIZONS
          </div>

          <h2 className="text-3xl sm:text-5xl lg:text-6xl font-serif text-white tracking-[-0.02em] font-normal leading-[1.08] mb-4">
            Six Living Horizons. Real In-Engine Survival.
          </h2>

          <p className="text-zinc-400 text-sm sm:text-base leading-relaxed max-w-2xl">
            From the 320-block vertical alpine spires of Terralith to subterranean amethyst abysses at Y=-64 and sub-zero extrasolar colonies on Glacio—explore the actual living landscapes active on the Ventrix: Frontier server.
          </p>
        </div>

        {/* In-Engine Survival Reality Verification Callout */}
        <div className="p-4 rounded-2xl bg-[#090b10]/90 border border-white/10 backdrop-blur-xl shadow-xl shrink-0 self-start md:self-auto max-w-xs text-left">
          <div className="flex items-center gap-2 mb-1.5">
            <span className="relative flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75" />
              <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-400" />
            </span>
            <span className="text-[11px] font-mono uppercase tracking-wider text-emerald-400 font-medium">
              100% Active In-Engine World
            </span>
          </div>
          <p className="text-[11px] text-zinc-400 leading-relaxed font-sans">
            Every vista is generated by the server’s Terralith engine with path-traced shaders. Verifiable live via 3D BlueMap.
          </p>
        </div>
      </div>

      {/* Horizon Selector Pill Strip */}
      <div className="relative z-10 flex items-center gap-2 overflow-x-auto pb-4 pt-1 mb-8 no-scrollbar scroll-smooth">
        {HORIZONS.map((h, idx) => {
          const isSelected = activeIndex === idx;
          return (
            <button
              key={h.id}
              onClick={() => handleSelect(idx)}
              className={`flex items-center gap-2 px-4 py-2.5 rounded-full text-xs font-mono tracking-tight shrink-0 border cursor-pointer select-none transition-all duration-300 [transition-timing-function:cubic-bezier(0.16,1,0.3,1)] active:scale-[0.97] ${
                isSelected
                  ? "bg-white text-black font-semibold border-white shadow-lg shadow-white/10"
                  : "bg-white/[0.03] text-zinc-400 hover:text-white border-white/[0.08] hover:border-white/[0.2] hover:bg-white/[0.06]"
              }`}
            >
              <span className={`text-[10px] font-mono ${isSelected ? "text-zinc-600" : "text-zinc-500"}`}>
                0{idx + 1}
              </span>
              <span>{h.name}</span>
            </button>
          );
        })}
      </div>

      {/* Main Panoramic Viewport & Editorial Split Stage */}
      <div className="relative z-10 rounded-[32px] sm:rounded-[36px] border border-white/10 bg-[#090b10]/95 shadow-[0_34px_90px_rgba(0,0,0,0.85)] overflow-hidden backdrop-blur-2xl">
        {/* Specular Top Rim Highlight */}
        <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-white/25 to-transparent pointer-events-none z-20" />

        <div className="grid grid-cols-1 lg:grid-cols-12 items-stretch">
          {/* Left: Panoramic 16:10 Cinematic Viewport (7 cols) */}
          <div className="lg:col-span-7 relative group min-h-[340px] sm:min-h-[460px] lg:min-h-[580px] overflow-hidden bg-black flex items-center justify-center">
            <AnimatePresence mode="wait">
              <motion.div
                key={activeHorizon.id}
                initial={{ opacity: 0, scale: 1.04 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.98 }}
                transition={{ duration: 0.65, ease: [0.16, 1, 0.3, 1] }}
                className="absolute inset-0 cursor-pointer"
                onClick={() => {
                  playHapticClick();
                  setLightboxOpen(true);
                }}
              >
                <Image
                  src={activeHorizon.imageSrc}
                  alt={activeHorizon.title}
                  fill
                  priority
                  sizes="(max-width: 1024px) 100vw, 60vw"
                  className="object-cover object-center transition-transform duration-700 [transition-timing-function:cubic-bezier(0.16,1,0.3,1)] group-hover:scale-[1.03]"
                />

                {/* Soft gradient vignetting */}
                <div className="absolute inset-0 bg-gradient-to-t from-[#090b10] via-transparent to-black/30 pointer-events-none" />
                <div className="absolute inset-0 bg-gradient-to-r from-transparent via-transparent to-[#090b10] hidden lg:block pointer-events-none" />
              </motion.div>
            </AnimatePresence>

            {/* Top-Left Floating Location Badge */}
            <div className="absolute top-5 left-5 z-20 flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-black/70 border border-white/15 backdrop-blur-xl text-[11px] font-mono text-zinc-200 shadow-xl">
              <MapPin className="w-3.5 h-3.5 text-emerald-400" />
              <span>{activeHorizon.name}</span>
            </div>

            {/* Top-Right Fullscreen Lightbox Button */}
            <button
              onClick={() => {
                playHapticClick();
                setLightboxOpen(true);
              }}
              className="absolute top-5 right-5 z-20 flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-black/70 hover:bg-black/90 border border-white/15 hover:border-white/30 backdrop-blur-xl text-[11px] font-mono text-zinc-300 hover:text-white transition-all cursor-pointer shadow-xl active:scale-[0.95]"
              title="Inspect 8K Fullscreen Lightbox"
            >
              <Maximize2 className="w-3.5 h-3.5" />
              <span className="hidden sm:inline">Inspect 8K</span>
            </button>

            {/* Bottom Carousel Arrow Controls */}
            <div className="absolute bottom-5 left-5 z-20 flex items-center gap-2">
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  handlePrev();
                }}
                className="w-9 h-9 rounded-full bg-black/70 hover:bg-white hover:text-black border border-white/15 text-white flex items-center justify-center backdrop-blur-xl transition-all duration-200 active:scale-[0.92] cursor-pointer shadow-lg"
                aria-label="Previous Horizon"
              >
                <ChevronLeft className="w-4 h-4" />
              </button>
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  handleNext();
                }}
                className="w-9 h-9 rounded-full bg-black/70 hover:bg-white hover:text-black border border-white/15 text-white flex items-center justify-center backdrop-blur-xl transition-all duration-200 active:scale-[0.92] cursor-pointer shadow-lg"
                aria-label="Next Horizon"
              >
                <ChevronRight className="w-4 h-4" />
              </button>
              <span className="text-[11px] font-mono text-zinc-400 px-2 py-1 rounded bg-black/60 border border-white/10 backdrop-blur-md">
                0{activeIndex + 1} / 0{HORIZONS.length}
              </span>
            </div>
          </div>

          {/* Right: Editorial & Telemetry Column (5 cols) */}
          <div className="lg:col-span-5 p-6 sm:p-8 lg:p-10 flex flex-col justify-between space-y-6 text-left relative z-10 border-t lg:border-t-0 lg:border-l border-white/[0.08]">
            <AnimatePresence mode="wait">
              <motion.div
                key={activeHorizon.id}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -6 }}
                transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}
                className="space-y-5"
              >
                {/* Kicker */}
                <div className={`inline-flex items-center gap-2 px-3 py-1 rounded-full border font-mono text-[11px] uppercase tracking-widest ${badgeColorClasses[activeHorizon.bloomColor]}`}>
                  <Sparkles className="w-3 h-3" />
                  <span>{activeHorizon.kicker}</span>
                </div>

                {/* Title */}
                <h3 className="text-2xl sm:text-4xl font-serif text-white tracking-[-0.02em] font-normal leading-[1.12]">
                  {activeHorizon.title}
                </h3>

                {/* Editorial Description */}
                <p className="text-zinc-300 text-sm sm:text-base font-normal leading-relaxed">
                  {activeHorizon.description}
                </p>

                {/* Telemetry Matrix Grid */}
                <div className="p-4 rounded-2xl bg-black/50 border border-white/[0.08] space-y-3 font-mono text-xs backdrop-blur-md">
                  <div className="flex items-center justify-between pb-2.5 border-b border-white/[0.06]">
                    <span className="text-zinc-500 uppercase tracking-wider text-[10px]">Elevation Range</span>
                    <span className="text-white font-medium">{activeHorizon.elevation}</span>
                  </div>

                  <div className="flex items-center justify-between pb-2.5 border-b border-white/[0.06]">
                    <span className="text-zinc-500 uppercase tracking-wider text-[10px]">Hazard Profile</span>
                    <span className="text-rose-300/90 text-right">{activeHorizon.hazard}</span>
                  </div>

                  <div className="flex items-center justify-between pb-2.5 border-b border-white/[0.06]">
                    <span className="text-zinc-500 uppercase tracking-wider text-[10px]">Strategic Yield</span>
                    <span className="text-emerald-400 text-right">{activeHorizon.yield}</span>
                  </div>

                  <div className="flex items-center justify-between">
                    <span className="text-zinc-500 uppercase tracking-wider text-[10px]">Dominant Infrastructure</span>
                    <span className="text-zinc-200 text-right">{activeHorizon.infrastructure}</span>
                  </div>
                </div>
              </motion.div>
            </AnimatePresence>

            {/* Action Buttons */}
            <div className="pt-4 border-t border-white/[0.06] flex flex-wrap items-center gap-3">
              {onOpenBlueMapModal && (
                <button
                  onClick={() => {
                    playHapticClick();
                    onOpenBlueMapModal();
                  }}
                  className="flex-1 flex items-center justify-center gap-2 py-3 px-4 rounded-full bg-white/[0.04] hover:bg-white/[0.08] border border-white/[0.1] hover:border-white/[0.22] text-xs font-mono uppercase tracking-wider text-white transition-all active:scale-[0.98] cursor-pointer select-none group"
                >
                  <Globe className="w-3.5 h-3.5 text-cyan-400" />
                  <span>Trace Coordinates on 3D BlueMap</span>
                  <ArrowRight className="w-3.5 h-3.5 transition-transform group-hover:translate-x-1" />
                </button>
              )}

              {onOpenJoinModal && (
                <button
                  onClick={() => {
                    playHapticClick();
                    onOpenJoinModal();
                  }}
                  className="px-5 py-3 rounded-full bg-white hover:bg-zinc-200 active:bg-zinc-300 text-black text-xs font-semibold font-mono uppercase tracking-wider transition-all active:scale-[0.98] cursor-pointer select-none shadow-sm"
                >
                  <span>Explore Now</span>
                </button>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* Fullscreen 8K Lightbox Modal */}
      <AnimatePresence>
        {lightboxOpen && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.3 }}
            className="fixed inset-0 z-[1200] bg-black/95 backdrop-blur-3xl flex flex-col items-center justify-between p-4 sm:p-6 lg:p-8 select-none"
            onClick={() => setLightboxOpen(false)}
          >
            {/* Top Lightbox Header */}
            <div
              className="w-full max-w-7xl flex items-center justify-between text-xs font-mono text-zinc-300 z-10"
              onClick={(e) => e.stopPropagation()}
            >
              <div className="flex items-center gap-3">
                <span className="w-2.5 h-2.5 rounded-full bg-emerald-400 animate-pulse" />
                <span className="text-white font-semibold">{activeHorizon.name}</span>
                <span className="text-zinc-600 hidden sm:inline">•</span>
                <span className="text-zinc-400 hidden sm:inline">{activeHorizon.elevation}</span>
              </div>

              <div className="flex items-center gap-3">
                <span className="text-zinc-500 hidden sm:inline">Use [←] and [→] arrows • [ESC] to close</span>
                <button
                  onClick={() => setLightboxOpen(false)}
                  className="w-9 h-9 rounded-full bg-white/10 hover:bg-white/20 border border-white/15 text-white flex items-center justify-center transition-colors cursor-pointer"
                  aria-label="Close Lightbox"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>
            </div>

            {/* Center Stage Image */}
            <div
              className="relative w-full max-w-6xl aspect-[16/10] my-auto rounded-3xl overflow-hidden border border-white/15 shadow-[0_34px_120px_rgba(0,0,0,0.95)]"
              onClick={(e) => e.stopPropagation()}
            >
              <AnimatePresence mode="wait">
                <motion.div
                  key={activeHorizon.id}
                  initial={{ opacity: 0, scale: 0.98 }}
                  animate={{ opacity: 1, scale: 1 }}
                  exit={{ opacity: 0, scale: 1.02 }}
                  transition={{ duration: 0.4 }}
                  className="relative w-full h-full"
                >
                  <Image
                    src={activeHorizon.imageSrc}
                    alt={activeHorizon.title}
                    fill
                    priority
                    quality={100}
                    sizes="95vw"
                    className="object-contain object-center"
                  />
                </motion.div>
              </AnimatePresence>

              {/* Prev / Next Floating Arrows in Lightbox */}
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  handlePrev();
                }}
                className="absolute left-4 top-1/2 -translate-y-1/2 w-12 h-12 rounded-full bg-black/60 hover:bg-white hover:text-black border border-white/20 text-white flex items-center justify-center backdrop-blur-xl transition-all active:scale-[0.92] cursor-pointer shadow-2xl"
                aria-label="Previous image"
              >
                <ChevronLeft className="w-6 h-6" />
              </button>
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  handleNext();
                }}
                className="absolute right-4 top-1/2 -translate-y-1/2 w-12 h-12 rounded-full bg-black/60 hover:bg-white hover:text-black border border-white/20 text-white flex items-center justify-center backdrop-blur-xl transition-all active:scale-[0.92] cursor-pointer shadow-2xl"
                aria-label="Next image"
              >
                <ChevronRight className="w-6 h-6" />
              </button>
            </div>

            {/* Bottom Thumbnail Strip */}
            <div
              className="w-full max-w-4xl flex items-center justify-center gap-2 overflow-x-auto py-2 z-10 no-scrollbar"
              onClick={(e) => e.stopPropagation()}
            >
              {HORIZONS.map((h, i) => (
                <button
                  key={h.id}
                  onClick={() => handleSelect(i)}
                  className={`relative w-20 sm:w-24 aspect-[16/10] rounded-xl overflow-hidden border transition-all cursor-pointer ${
                    activeIndex === i
                      ? "border-white ring-2 ring-white/50 scale-105"
                      : "border-white/20 opacity-50 hover:opacity-100 hover:border-white/40"
                  }`}
                >
                  <Image
                    src={h.imageSrc}
                    alt={h.name}
                    fill
                    sizes="96px"
                    className="object-cover"
                  />
                </button>
              ))}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </section>
  );
}
